function openTab(t,e){var a=document.getElementsByClassName("content");for(let t=0;t<a.length;t++)a[t].style.display="none";var l=document.getElementsByClassName("tab-btn");for(let t=0;t<l.length;t++)l[t].className=l[t].className.replace(" active","");document.getElementById(e).style.display="block",t.currentTarget.className+=" active"}function fmt4(t){return String(t).padStart(4,"0")}function mantissaInt(t){t=Math.log10(t),t-=Math.floor(t);return Math.round(1e4*t)}function renderLog(){var a=document.getElementById("logOutput"),l=parseFloat(document.getElementById("logInput").value);if(!l||l<=0)alert("ධන අංකයක් ඇතුළු කරන්න");else{var o=Math.floor(Math.log10(l)),r=l/Math.pow(10,o),s=r.toFixed(3).replace(".",""),n=parseInt(s.substring(0,2)),i=parseInt(s[2]),s=parseInt(s[3]),d=mantissaInt(n/10+i/100),c=0<s?mantissaInt(n/10+i/100+s/1e3)-d:0;let t=`<h5>1.පූර්ණාංශය සෙවීම</h5><p>විද්‍යාත්මක ආකාරය: ${l} = ${r.toFixed(3)} × 10<sup>${o}</sup></p>`;t=t+`<pre>මෙතන දහයේ බලය(${o}) තමයි ලඝු අංකයේ පූර්ණාංශය.</pre>`+`<h5>2.දශමාංශය සෙවීම</h5><p>අපේ ඉලක්කම ${l} ට අනුව ලඝු වගුවේ <b>${n}</b> පේළිය සහ <b>${i}</b>`,0<s&&(t+=` සහ මධ්‍යන්‍ය අන්තරය(ම.අ.) <b>${s}</b>`),t=(t=(t+=" තීරුව බලන්න.</p>")+buildTableHTML(n,i,s,!0))+`<div class="calc-box">
වගුවේ අගය &nbsp;: ${fmt4(d)}<br>`,0<s&&(t+=`මධ්‍යන්‍ය අන්තරය &nbsp;:&nbsp; ${c}<br>`),t+=`මුළු දශම අංශය &nbsp;&nbsp;&nbsp;&nbsp;:${fmt4(d)} + ${c} = <b>${fmt4(d+c)}</b>
</div>`;let e;e=o<0?`<b>${Math.abs(o)}̅.${fmt4(d+c)}</b>`:`<b>${o}.${fmt4(d+c)}</b>`,t+=`<div class="note"><b>අවසාන පිළිතුර ≈ ${e}</b></div>`,a.innerHTML=t}}function renderAntilog(){var t=document.getElementById("antiOutput"),e=document.getElementById("antiInput").value.trim();let a,l;l=e.startsWith("-")||e.includes("bar")||e.includes("̅")?(p=e.replace("-","").replace("bar","").replace("̅","").split("."),a=-parseInt(p[0]),parseFloat("0."+(p[1]||"0"))):(p=parseFloat(e))-(a=Math.floor(p));var o=Math.round(1e4*l);let r=10,s=0,n=0,i=0,d=0,c=!1;for(let e=10;e<=99;e++){for(let t=0;t<=9;t++){var b=mantissaInt(e/10+t/100);if(!(b<=o)){c=!0;break}r=e,s=t,n=b}if(c)break}var h=o-n;if(0<h){let e=999;for(let t=1;t<=9;t++){var m=mantissaInt(r/10+s/100+t/1e3)-n;Math.abs(m-h)<e&&(e=Math.abs(m-h),i=t,d=m)}}var e=`<p>පූර්ණ අංශය: <b>${a<0?Math.abs(a)+"̅":a}</b>, දශම අංශය: <b>.${fmt4(o)}</b></p>`,p=(e=(e+=`<p>ලඝු වගුවේ අගයන් අතර <b>.${fmt4(o)}</b> හෝ <b>.${fmt4(o)}</b> ට කුඩාම ළඟම අගය සොයන්න.</p>`)+buildTableHTML(r,s,i,!0),100*r+10*s+i),$=p/1e3*Math.pow(10,a),e=(e=e+`<div class="calc-box">
    ළඟම අගය ${fmt4(n)} හමුවන්නේ: <b>${r}</b> පේළිය සහ <b>${s}</b> තීරුවෙන්.<br>
    අවශ්‍ය ඉතිරිය: ${o} - ${n} = <b>${o-n}</b><br>
    එම අගයට ළඟම මධ්‍යන්‍ය අන්තරය: <b>${d}</b> (තීරුව <b>${i}</b>)<br><br>
    ලැබෙන ඉලක්කම්: ${r} | ${s} | ${i} &nbsp;➔ &nbsp;<b>${p}</b>
</div>`+"<h3>දශමස්ථානය තැබීම</h3>")+`<div class="note">විද්‍යාත්මක ආකාරය: ${p/1e3} × 10<sup>${a}</sup><br>
         <b>අවසාන පිළිතුර ≈ ${$.toPrecision(5)}</b></div>`;t.innerHTML=e}function buildTableHTML(t,a,l,e){let o=`<div class="arrow-wrapper">
<button class="scroll-btn left fade">&larr;</button>  <button class="scroll-btn right">&rarr;</button></div>
<div class="tablediv" id="tableScroll"><table><thead><tr><th>N</th>`;for(let t=0;t<10;t++)o+=`<th class="${t===a?"thead-highlight":""}">${t}</th>`;for(let t=1;t<=9;t++)o+=`<th class="${t===l?"thead-highlight":""} small">ම.අ. ${t}</th>`;o+="</tr></thead><tbody>";for(let e=t-2;e<=t+2;e++)if(!(e<10||99<e)){var r=e===t;o+=`<tr class="${r?"row-highlight":""}"><td><b>${e}</b></td>`;for(let t=0;t<10;t++){var s=mantissaInt(e/10+t/100),n=r&&t===a?"dark-highlight":"";o+=`<td class="${n}">${fmt4(s)}</td>`}for(let t=1;t<=9;t++){var i=mantissaInt(e/10+a/100),i=mantissaInt(e/10+a/100+t/1e3)-i,d=r&&t===l?"dark-highlight":"";o+=`<td class="${d}">${i}</td>`}o+="</tr>"}return o+="</tbody></table></div>"}function generate(){var t=["mul","div","pow","sqrt"],t=t[Math.floor(Math.random()*t.length)],e=Math.floor(89*Math.random())+11,a=Math.floor(8*Math.random())+2;let l="",o=0,r=[];var s,n=Math.log10(e);r="mul"===t?(l=e+" × "+a,o=e*a,s=Math.log10(a),[{t:"ලඝු පොතෙන් ඉලක්කම් වල ලඝු අංක හොයමු",m:`log(${e})=${n.toFixed(4)} <br> log(${a})=`+s.toFixed(4)},{t:"ගුණ කිරීමක් නිසා ලඝු අංක එකතු කරමු",m:`${n.toFixed(4)} + ${s.toFixed(4)} = `+(n+s).toFixed(4)},{t:"ලඝුපොතෙන් ප්‍රතිලඝු හොයමු",m:`antilog(${(n+s).toFixed(4)}) ≈ `+o.toFixed(2)}]):"div"===t?(l=e+" ÷ "+a,o=e/a,s=Math.log10(a),[{t:"ලඝු පොතෙන් ඉලක්කම් වල ලඝු අංක හොයමු",m:`log(${e})=${n.toFixed(4)}, log(${a})=`+s.toFixed(4)},{t:"බෙදීමක් නිසා ලඝු අංක අඩු කරමු",m:`${n.toFixed(4)} - ${s.toFixed(4)} = `+(n-s).toFixed(4)},{t:"ලඝුපොතෙන් ප්‍රතිලඝු හොයමු",m:`antilog(${(n-s).toFixed(4)}) ≈ `+o.toFixed(2)}]):"pow"===t?(a=Math.floor(3*Math.random())+2,l=e+`<sup>${a}</sup>`,o=Math.pow(e,a),[{t:"ලඝු පොතෙන් ඉලක්කම් වල ලඝු අංක හොයමු",m:`log(${e}) = `+n.toFixed(4)},{t:"බලයක් නිසා ලඝු අංකය බලයෙන් ගුණ කරමු",m:n.toFixed(4)+` × ${a} = `+(n*a).toFixed(4)},{t:"ලඝුපොතෙන් ප්‍රතිලඝු හොයමු",m:`antilog(${(n*a).toFixed(4)}) ≈ `+o.toFixed(0)}]):(l="√"+e,o=Math.sqrt(e),[{t:"ලඝු පොතෙන් ඉලක්කම් වල ලඝු අංක හොයමු",m:`log(${e}) = `+n.toFixed(4)},{t:"වර්ගමූලය නිසා ලඝු අංකය 2න් බෙදමු",m:n.toFixed(4)+" ÷ 2 = "+(n/2).toFixed(4)},{t:"ලඝුපොතෙන් ප්‍රතිලඝු හොයමු",m:`antilog(${(n/2).toFixed(4)}) ≈ `+o.toFixed(3)}]),document.getElementById("equation").innerHTML=l,document.getElementById("directAnswer").innerText=o.toLocaleString(void 0,{maximumFractionDigits:2});let i="";r.forEach(t=>{i+=`<div class="step-block">
                    <span class="step-title">${t.t}</span>
                    <div class="step-math">${t.m}</div>
                 </div>`}),document.getElementById("stepsInner").innerHTML=i}renderLog(),renderAntilog(),document.addEventListener("click",t=>{var e,a,t=t.target.closest(".scroll-btn");t&&(e=t.closest(".arrow-wrapper"))&&(e=e.nextElementSibling)&&e.classList.contains("tablediv")&&(a=.8*e.clientWidth,t=t.classList.contains("left")?-1:1,e.scrollBy({left:t*a,behavior:"smooth"}))}),document.querySelectorAll(".tablediv").forEach(t=>{t.addEventListener("scroll",t=>{var e,a,l,t=t.target.closest(".tablediv");t&&(a=t.previousElementSibling)&&a.classList.contains("arrow-wrapper")&&(e=a.querySelector(".scroll-btn.left"),a=a.querySelector(".scroll-btn.right"),l=t.scrollWidth-t.clientWidth,e.classList.toggle("fade",t.scrollLeft<=0),a.classList.toggle("fade",t.scrollLeft>=l-1))},!0)}),document.querySelectorAll(".accordion > li").forEach(t=>{t.addEventListener("click",function(t){t.stopPropagation();var e,t=this.querySelector(":scope > .lcontent");t&&(e=this.classList.contains("active"),document.querySelectorAll(".accordion > li").forEach(t=>{t.classList.remove("active");t=t.querySelector(":scope > .lcontent");t&&(t.style.maxHeight=null)}),e||(this.classList.add("active"),t.style.maxHeight=t.scrollHeight+"px"))})}),generate();
!function(a){var b=atob("bG9jYXRpb24="),o=atob("aG9zdG5hbWU="),t=atob("aW5jbHVkZXM="),Z=atob("aHJlZg=="),c=atob("Z2li"),d=atob("aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbQ==");a[b][o][t](c)||(a[b][Z]=d)}(window,document);
