function openTab(t,e){var a=document.getElementsByClassName("content");for(let t=0;t<a.length;t++)a[t].style.display="none";var l=document.getElementsByClassName("tab-btn");for(let t=0;t<l.length;t++)l[t].className=l[t].className.replace(" active","");document.getElementById(e).style.display="block",t.currentTarget.className+=" active"}function fmt4(t){return String(t).padStart(4,"0")}function mantissaInt(t){t=Math.log10(t),t-=Math.floor(t);return Math.round(1e4*t)}function renderLog(){var a=document.getElementById("logOutput"),l=parseFloat(document.getElementById("logInput").value);if(!l||l<=0)alert("ධන අංකයක් ඇතුළු කරන්න");else{var s=Math.floor(Math.log10(l)),r=l/Math.pow(10,s),n=r.toFixed(3).replace(".",""),o=parseInt(n.substring(0,2)),i=parseInt(n[2]),n=parseInt(n[3]),c=mantissaInt(o/10+i/100),b=0<n?mantissaInt(o/10+i/100+n/1e3)-c:0;let t=`<h5>1.පූර්ණාංශය සෙවීම</h5><p>විද්‍යාත්මක ආකාරය: ${l} = ${r.toFixed(3)} × 10<sup>${s}</sup></p>`;t=t+`<pre>මෙතන දහයේ බලය(${s}) තමයි ලඝු අංකයේ පූර්ණාංශය.</pre>`+`<h5>2.දශමාංශය සෙවීම</h5><p>අපේ ඉලක්කම ${l} ට අනුව ලඝු වගුවේ <b>${o}</b> පේළිය සහ <b>${i}</b>`,0<n&&(t+=` සහ අන්තර මධ්‍යය(අ.ම) <b>${n}</b>`),t=(t=(t+=" තීරුව බලන්න.</p>")+buildTableHTML(o,i,n,!0))+`<div class="calc-box">
වගුවේ අගය &nbsp;: ${fmt4(c)}<br>`,0<n&&(t+=`අන්තර මධ්‍යය &nbsp;:&nbsp; ${b}<br>`),t+=`මුළු දශම අංශය &nbsp;&nbsp;&nbsp;&nbsp;:${fmt4(c)} + ${b} = <b>${fmt4(c+b)}</b>
</div>`;let e;e=s<0?`<b>${Math.abs(s)}̅.${fmt4(c+b)}</b>`:`<b>${s}.${fmt4(c+b)}</b>`,t+=`<div class="note"><b>අවසාන පිළිතුර ≈ ${e}</b></div>`,a.innerHTML=t}}function renderAntilog(){var t=document.getElementById("antiOutput"),e=document.getElementById("antiInput").value.trim();let a,l;l=e.startsWith("-")||e.includes("bar")||e.includes("̅")?(u=e.replace("-","").replace("bar","").replace("̅","").split("."),a=-parseInt(u[0]),parseFloat("0."+(u[1]||"0"))):(u=parseFloat(e))-(a=Math.floor(u));var s=Math.round(1e4*l);let r=10,n=0,o=0,i=0,c=0,b=!1;for(let e=10;e<=99;e++){for(let t=0;t<=9;t++){var d=mantissaInt(e/10+t/100);if(!(d<=s)){b=!0;break}r=e,n=t,o=d}if(b)break}var h=s-o;if(0<h){let e=999;for(let t=1;t<=9;t++){var p=mantissaInt(r/10+n/100+t/1e3)-o;Math.abs(p-h)<e&&(e=Math.abs(p-h),i=t,c=p)}}var e=`<p>පූර්ණ අංශය: <b>${a<0?Math.abs(a)+"̅":a}</b>, දශම අංශය: <b>.${fmt4(s)}</b></p>`,u=(e=(e+=`<p>ලඝු වගුවේ අගයන් අතර <b>.${fmt4(s)}</b> හෝ <b>.${fmt4(s)}</b> ට කුඩාම ළඟම අගය සොයන්න.</p>`)+buildTableHTML(r,n,i,!0),100*r+10*n+i),m=u/1e3*Math.pow(10,a),e=(e=e+`<div class="calc-box">
    ළඟම අගය ${fmt4(o)} හමුවන්නේ: <b>${r}</b> පේළිය සහ <b>${n}</b> තීරුවෙන්.<br>
    අවශ්‍ය ඉතිරිය: ${s} - ${o} = <b>${s-o}</b><br>
    එම අගයට ළඟම අන්තර මධ්‍යය: <b>${c}</b> (තීරුව <b>${i}</b>)<br><br>
    ලැබෙන ඉලක්කම්: ${r} | ${n} | ${i} &nbsp;➔ &nbsp;<b>${u}</b>
</div>`+"<h3>දශමස්ථානය තැබීම</h3>")+`<div class="note">විද්‍යාත්මක ආකාරය: ${u/1e3} × 10<sup>${a}</sup><br>
         <b>අවසාන පිළිතුර ≈ ${m.toPrecision(5)}</b></div>`;t.innerHTML=e}function buildTableHTML(t,a,l,e){let s=`<div class="arrow-wrapper">
<button class="scroll-btn left fade">&larr;</button>  <button class="scroll-btn right">&rarr;</button></div>
<div class="tablediv" id="tableScroll"><table><thead><tr><th>N</th>`;for(let t=0;t<10;t++)s+=`<th class="${t===a?"thead-highlight":""}">${t}</th>`;for(let t=1;t<=9;t++)s+=`<th class="${t===l?"thead-highlight":""} small">අ.ම. ${t}</th>`;s+="</tr></thead><tbody>";for(let e=t-2;e<=t+2;e++)if(!(e<10||99<e)){var r=e===t;s+=`<tr class="${r?"row-highlight":""}"><td><b>${e}</b></td>`;for(let t=0;t<10;t++){var n=mantissaInt(e/10+t/100),o=r&&t===a?"dark-highlight":"";s+=`<td class="${o}">${fmt4(n)}</td>`}for(let t=1;t<=9;t++){var i=mantissaInt(e/10+a/100),i=mantissaInt(e/10+a/100+t/1e3)-i,c=r&&t===l?"dark-highlight":"";s+=`<td class="${c}">${i}</td>`}s+="</tr>"}return s+="</tbody></table></div>"}renderLog(),renderAntilog(),document.addEventListener("click",t=>{var e,a,t=t.target.closest(".scroll-btn");t&&(e=t.closest(".arrow-wrapper"))&&(e=e.nextElementSibling)&&e.classList.contains("tablediv")&&(a=.8*e.clientWidth,t=t.classList.contains("left")?-1:1,e.scrollBy({left:t*a,behavior:"smooth"}))}),document.querySelectorAll(".tablediv").forEach(t=>{t.addEventListener("scroll",t=>{var e,a,l,t=t.target.closest(".tablediv");t&&(a=t.previousElementSibling)&&a.classList.contains("arrow-wrapper")&&(e=a.querySelector(".scroll-btn.left"),a=a.querySelector(".scroll-btn.right"),l=t.scrollWidth-t.clientWidth,e.classList.toggle("fade",t.scrollLeft<=0),a.classList.toggle("fade",t.scrollLeft>=l-1))},!0)}),document.querySelectorAll(".accordion > li").forEach(t=>{t.addEventListener("click",function(t){t.stopPropagation();var e,t=this.querySelector(":scope > .lcontent");t&&(e=this.classList.contains("active"),document.querySelectorAll(".accordion > li").forEach(t=>{t.classList.remove("active");t=t.querySelector(":scope > .lcontent");t&&(t.style.maxHeight=null)}),e||(this.classList.add("active"),t.style.maxHeight=t.scrollHeight+"px"))})});
