const DEFAULT_TEMPLATE="tpl-modern",DEFAULT_COLOR="blue";let settingsPromise=null;function getSetting(){return settingsPromise=settingsPromise||(async()=>{if(schoolId)try{var e=(await db.ref(`schools/${schoolId}/details`).once("value")).val();if(e)return e}catch(e){console.error("Failed to fetch settings:",e)}return{template:DEFAULT_TEMPLATE,color:DEFAULT_COLOR}})()}function toggleCustomUrlInput(){var e=document.querySelector('input[name="qrType"][value="custom"]'),t=document.getElementById("customUrlWrapper");t&&(t.style.display=e&&e.checked?"block":"none")}document.addEventListener("DOMContentLoaded",async()=>{var e=await getSetting(),t=("function"==typeof applyTemplateToCard&&applyTemplateToCard(e.template),"function"==typeof applyColorToCard&&applyColorToCard(e.color),"function"==typeof applyLogoToCard&&applyLogoToCard(e.logoUrl),"function"==typeof applyCoverToCard&&applyCoverToCard(e.coverUrl),Array.isArray(e.frontFields)?e.frontFields:DEFAULT_FRONT_KEYS),t=(initCardFieldSelectors(t,Array.isArray(e.backFields)?e.backFields:DEFAULT_BACK_KEYS),e.qrType||"default"),e=e.qrCustomUrl||"",t=document.querySelector(`input[name="qrType"][value="${t}"]`),t=(t&&(t.checked=!0),document.getElementById("qrCustomUrl"));t&&(t.value=e),toggleCustomUrlInput()});const EXCLUDED_KEYS=["y","z","A","B","D"],DEFAULT_FRONT_KEYS=["i","b","h"],DEFAULT_BACK_KEYS=["e","f","d","g"],SAMPLE_PREVIEW_DATA={fullName:"JOHN DOE",dob:"12/05/2012",gender:"Male",studentContact:"0771234567",fatherName:"Robert Doe",motherName:"Jane Doe",address:"123 School Lane, City",class:"10-A",admissionNo:"ADM-4502",birthCertNo:"BC-998811",admissionYear:"2018",admissionGrade:"Grade 1",positionsHeld:"Prefect",discipline:"Good",medical:"None",fatherNic:"851234567V",motherNic:"875643210V",guardianName:"Robert Doe",guardianNic:"851234567V",gnDivision:"GN-102",dsDivision:"DS-Puttalam",lowIncome:"No",aswesuma:"Eligible",siblings:"1"};function formatLabel(e){var t={dob:"Birthday",admissionNo:"Adm No",birthCertNo:"Birth Cert No",fatherNic:"Father NIC",motherNic:"Mother NIC",guardianNic:"Guardian NIC",gnDivision:"GN Division",dsDivision:"DS Division",fatherName:"Father",motherName:"Mother"};return t[e]||e.replace(/([A-Z])/g," $1").replace(/^./,e=>e.toUpperCase())}function initCardFieldSelectors(a=DEFAULT_FRONT_KEYS,n=DEFAULT_BACK_KEYS){const r=document.getElementById("frontFieldsContainer"),l=document.getElementById("backFieldsContainer");if(r&&l){r.innerHTML="",l.innerHTML="";const d=MODULE_FIELD_MAPS.students;Object.keys(d).forEach(e=>{var t,o;EXCLUDED_KEYS.includes(e)||(t=formatLabel(d[e]),o=a.includes(e)?"checked":"",r.insertAdjacentHTML("beforeend",`
      <label class="checkbox-item">
        <input type="checkbox" name="frontFields" value="${e}" ${o} onchange="updateCardPreview()">
        <span>${t}</span>
      </label>
    `),o=n.includes(e)?"checked":"",l.insertAdjacentHTML("beforeend",`
      <label class="checkbox-item">
        <input type="checkbox" name="backFields" value="${e}" ${o} onchange="updateCardPreview()">
        <span>${t}</span>
      </label>
    `))}),updateCardPreview()}}function getSelectedFieldKeys(e){return Array.from(document.querySelectorAll(`input[name="${e}"]:checked`)).map(e=>e.value)}function updateCardPreview(){var e,t=document.getElementById("frontCardBody"),o=document.getElementById("backCardBody");const a=MODULE_FIELD_MAPS.students;t&&(e=getSelectedFieldKeys("frontFields"),t.innerHTML=e.map(e=>{e=a[e];return`
        <div class="info-row">
          <span class="label">${formatLabel(e)}:</span>
          <span class="value">${SAMPLE_PREVIEW_DATA[e]||"N/A"}</span>
        </div>
      `}).join("")),o&&(t=getSelectedFieldKeys("backFields"),o.innerHTML=t.map(e=>{e=a[e];return`
        <p><strong>${formatLabel(e)}:</strong> <span>${SAMPLE_PREVIEW_DATA[e]||"N/A"}</span></p>
      `}).join(""))}async function saveSetting(){if(schoolId){var e,t=document.getElementById("frontCard"),o=document.getElementById("templateSelect"),t=t&&t.getAttribute("data-color")||DEFAULT_COLOR,o=o&&o.value||DEFAULT_TEMPLATE,a=getSelectedFieldKeys("frontFields"),n=getSelectedFieldKeys("backFields"),r=document.querySelector('input[name="qrType"]:checked')?.value||"default",l=document.getElementById("qrCustomUrl")?.value.trim()||"",d={template:o,color:t,frontFields:a,backFields:n,qrType:r,qrCustomUrl:l,updatedAt:firebase.database.ServerValue.TIMESTAMP};try{await db.ref(`schools/${schoolId}/details`).update(d),"undefined"!=typeof syncEngine&&syncEngine&&(e={...await syncEngine.getSchoolDetails()||{},id:"info",template:o,color:t,frontFields:a,backFields:n,qrType:r,qrCustomUrl:l},syncEngine.saveToIDB("schoolDetails",e)),console.log("Settings saved successfully."),alertbox("Settings saved successfully!","success")}catch(e){console.error("Failed to save settings:",e),alertbox("Error saving settings.","error")}}else console.error("School ID missing!")}async function loadSavedSettings(){let e=DEFAULT_FRONT_KEYS,t=DEFAULT_BACK_KEYS;if(schoolId)try{var o,a,n,r=(await db.ref(`schools/${schoolId}/details`).once("value")).val();r&&(r.template&&(o=document.getElementById("templateSelect"))&&(o.value=r.template),r.color&&(a=document.getElementById("frontCard"),n=document.getElementById("backCard"),a&&a.setAttribute("data-color",r.color),n)&&n.setAttribute("data-color",r.color),Array.isArray(r.frontFields)&&(e=r.frontFields),Array.isArray(r.backFields))&&(t=r.backFields)}catch(e){console.error("Failed to load saved card settings from Firebase:",e)}else console.error("School ID missing!");initCardFieldSelectors(e,t)}function applyColorToCard(t){var e=document.getElementById("frontCard"),o=document.getElementById("backCard");e&&e.setAttribute("data-color",t),o&&o.setAttribute("data-color",t),document.querySelectorAll(".color-box").forEach(e=>{e.classList.toggle("active",e.classList.contains("color-"+t))})}function applyTemplateToCard(t){var e=document.getElementById("frontCard"),o=document.getElementById("backCard"),a=document.getElementById("templateSelect"),n=e=>{e.className=e.className.replace(/\btpl-\S+/g,"").trim(),e.classList.add(t)};e&&n(e),o&&n(o),a&&(a.value=t)}function applyAndSaveColor(e){applyColorToCard(e)}function applyAndSaveTemplate(e){applyTemplateToCard(e)}function applyLogoToCard(e){console.log(e);var t=document.getElementById("idLogo");t&&e&&(t.src=e)}function applyCoverToCard(e){var t=document.getElementById("frontCard");t&&(e?(t.style.background=`linear-gradient(rgba(255, 255, 255, 0.7), rgba(255, 255, 255, 0.9)), url('${e}')`,t.style.backgroundSize="cover",t.style.backgroundPosition="center"):t.style.background="")}document.addEventListener("DOMContentLoaded",()=>{loadSavedSettings()}),auth.onAuthStateChanged(e=>{var t=window.location.pathname.endsWith("admin.html");e||!navigator.onLine||t||(window.location.href="admin.html")});
