function renderTimetable(u,v,h){var e=["monday","tuesday","wednesday","thursday","friday"];const f={monday:"Monday",tuesday:"Tuesday",wednesday:"Wednesday",thursday:"Thursday",friday:"Friday"};if(v&&h)if(!u||"object"!=typeof u||Array.isArray(u))v.innerHTML=`
            <div class="day-empty">
                Free
            </div>
        `,h.innerHTML="";else{v.innerHTML="",h.innerHTML="";let y=0;function C(e){return e?Array.isArray(e)?e.map((e,a)=>({period:a,data:e})):"object"==typeof e?Object.entries(e).map(([e,a])=>({period:Number(e),data:a})).filter(e=>!isNaN(e.period)):[]:[]}e.forEach(e=>{var e=C(u[e]);e.length&&(e=Math.max(...e.map(e=>e.period)),y=Math.max(y,e))}),0===y?v.innerHTML=`
            <div class="day-empty">
                Free
            </div>
        `:e.forEach((a,e)=>{var t=C(u[a]),d=document.createElement("div"),n=(d.className="day-column",d.dataset.day=a,0===e&&d.classList.add("active"),document.createElement("div")),s=(n.className="day-header",document.createElement("div")),c=(s.className="day-name",s.textContent=f[a],t.filter(e=>e.data).length,n.appendChild(s),d.appendChild(n),document.createElement("div"));c.className="periods";for(let a=1;a<=y;a++){var i,r,l=t.find(e=>e.period===a),l=l?l.data:null,m=document.createElement("div"),o=(m.className="period",l||m.classList.add("empty"),document.createElement("div"));o.className="period-number",o.textContent=a,m.appendChild(o),l?((o=document.createElement("div")).className="period-info",(i=document.createElement("div")).className="subject",i.textContent=l.s||"Unknown subject",(r=document.createElement("div")).className="class-name",r.textContent=l.c||"",o.appendChild(i),o.appendChild(r),m.appendChild(o)):((l=document.createElement("div")).className="empty-text",l.textContent="Free",m.appendChild(l)),c.appendChild(m)}d.appendChild(c),v.appendChild(d);const p=document.createElement("button");p.className="day-btn",0===e&&p.classList.add("active"),p.textContent=f[a],p.addEventListener("click",()=>{var e;!p.classList.contains("active")&&(h.querySelectorAll(".day-btn").forEach(e=>{e.classList.remove("active")}),v.querySelectorAll(".day-column").forEach(e=>{e.classList.remove("active")}),p.classList.add("active"),e=v.querySelector(`.day-column[data-day="${a}"]`))&&e.classList.add("active")}),h.appendChild(p)})}}
